spring:
  application:
    name: TargetTracking
    
  datasource:
    url: jdbc:postgresql://localhost:5432/defense_db
    username: defense
    password: defense_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: target-tracking-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  exception-conversion-word: "%wEx{0}"

server:
  port: 8080
